### ISSUE TITLE
Removal of "no remelt" problems and logic

### ISSUE THREAD

**Issue by MattRolchigo** [LLNL/ExaCA#204]
Will require the following steps:

- [x] Remove the unneeded example files and subroutines for "no remelt" problems, adding a notice that all problems will use remelting (may require update to ExaCA-Data repository data) (also renders #95 no longer relevant)
- [X] Fix "debug"/printing of initial view data, which previously was set up only for "no remelt" problem types (also closes #104 )
- [x] Reorganize remaining views and subroutines for temperature data into a struct & Removal of redundant MeltTimeStep, CritTimeStep, and UndercoolingChange views (data is stored in LayerTimeTempHistory) #223
